// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jivshzkyrhmdmjumjfve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdnNoemt5cmhtZG1qdW1qZnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDYyMzcsImV4cCI6MjA3Mzk4MjIzN30.WfFftpgZaz9UsvXqh4sypK5IpHjakLVMDGxfo1zzcag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});